### PR TITLE
first updates

### PR DESCRIPTION
**Pull request by ZoeLeBlanc**

### CODE REVIEW

**Comment by ZoeLeBlanc** [comment]
I'm finished now. Can someone check it out?

**Comment by zoeames** [comment]
Hey name twin!

Really nice first quiz.  You have met all the requirements but I think there are two place you can clean the code up:
1.  add a little space around the product descriptions and specifications - they seem to be running right up against the border.  A little spacing will look cleaner
2.  In your CSS it looks like you very specifically targeted certain areas but because you are being so specific I am noticing a lot of code duplication.  Is there a way you can combine things?  For example you have .second header and .third header.  but those two selectors have the same css.  Is there a way you can make 1 class with the css and then use that class in your html in the 2 different places?

Give those two things a go and then let me know when you have changes pushed up and want me to take another look

**Comment by ZoeLeBlanc** [comment]
Hi Name-Twin @zoeames 

Think this is about as condensed as I can get with the code. Let me know if you see anywhere else you think I can make changes. Thanks for checking my quiz!

**Comment by zoeames** [comment]
name twin - this looks excellent!  very clean.  you are good to merge 👍

**Comment by ZoeLeBlanc** [comment]
Thanks :)

**Pull request merged**
